<a href="https://colab.research.google.com/github/Sayahniyas/DATASCIENCE_PROJECTS/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
arr = np.array([1,2,3,])
print(arr)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 > arr2)
print(arr1 == arr2)
print(arr1 != arr2)

In [ ]:
arr1 = np.array([[1,2,3],[5,6,7]]) #2 dimentional
arr2 = np.array([[1,2],[5,6],[8,9]])# 3 dimentional array
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3, 2)


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

In [ ]:
import numpy as np
arr = np.array([1,2,3,])
print(arr[0])

In [ ]:
#ramdom
import numpy as np
v = np.random.rand(7)
print(v)


[0.49996506 0.34291379 0.1089381  0.592938   0.12402113 0.71101069
 0.3161289 ]


In [ ]:
import numpy as np
arr = np.array( [[[1,2,3],
                [4,5,6],
                [5,8,9]]])
print(arr)
print(arr[0,1,1])

[[[1 2 3]
  [4 5 6]
  [5 8 9]]]
5


In [ ]:
arr1 = np.array([1,2,3,4,5,6,5,8,9])
print(arr1)
arr2 = arr1.reshape(3,3)

print(arr2)

[1 2 3 4 5 6 5 8 9]
[[1 2 3]
 [4 5 6]
 [5 8 9]]


In [ ]:
#pandas(panal data system)

import pandas as pd


> pandas is a open source python libary


1.   used for data cleaning,data analysis,data manipulation and data visualization perperation
2.   working with excel sheets or tabular formate data



pandas data structure



* series
* dataframe



series in a 1 dimentional labled array

In [ ]:
#series
import pandas as pd
marks= pd.Series([55,56,77,88,99,33])
print(marks)

0    55
1    56
2    77
3    88
4    99
5    33
dtype: int64


In [ ]:
import pandas as pd
s1= pd.Series([1,2,3,4],index = ['a','b','c','d'])
print(s1)

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
import pandas as pd
s1 = pd.Series(["Bca","Bcom","Bca"],index = ["ardra","krishna","hannan"])
print(s1)
print(s1["ardra"])

ardra       Bca
krishna    Bcom
hannan      Bca
dtype: object
Bca


questions:


1. what is numpy and pandas??
: numpy is a python libary thats is used for mathematical operations  pandas are also python libaray that is used for data data analysis,manipulation and data visualization
2. why do we use numpy and pandas? :numpy is used for large mathematical operations where as pandas are used to analize and visualize data  
3. what is series?: one dimetional and labeled array. it displays data with index either given or default  
4. what is the difference between list and numpy array?:
list can hold various datatypes. numpy can only hold one data type and is faster more effiecient than list
5. indexing and slicing?:
6. create a numpy array containing numbes from 1 to 20?
7. create a pandas series with doctors and dept?






In [ ]:
#6
import numpy as np
arr1 = np.arange(1,21)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#7
import pandas as pd
s1 = pd.Series(["Dr.shameena","Dr.amal","Dr.husna"], index = ["neurology","pediatrician","surgeon"])
print(s1)

neurology       Dr.shameena
pediatrician        Dr.amal
surgeon            Dr.husna
dtype: object


In [ ]:
import pandas as pd
data = [20,30,40,50]
s=pd.Series(data,index=['a','b','c','d']) #index aka position
print(s)


a    20
b    30
c    40
d    50
dtype: int64


In [ ]:
import pandas as pd
data = {20:"rinza", 30:"sreya", 40:"gayathri", 50:"arya"}  #no need of () and[]
s=pd.Series(data)
print(s)

20       rinza
30       sreya
40    gayathri
50        arya
dtype: object


loc and iloc



iloc default index base

loc manual index base





In [ ]:
data = [10, 20, 30, 40, 50]#no need of () and[]
s=pd.Series(data,index =[1,2,3,4,5])
print(s)


1    10
2    20
3    30
4    40
5    50
dtype: int64


In [ ]:
print(s.loc[1]) #given index
print(s.iloc[1:5]) #default index
print(s.loc[1:3]) # loc doesnot index rule

10
2    20
3    30
4    40
5    50
dtype: int64
1    10
2    20
3    30
dtype: int64


In [ ]:
data = [10,20,30.40]
s=pd.Series(data,index = ['a','b','c'])
print(s[s<30])
print(s.loc['a':'c'])
print(s.iloc[:2])
print(s[s>30])

a    10.0
b    20.0
dtype: float64
a    10.0
b    20.0
c    30.4
dtype: float64
a    10.0
b    20.0
dtype: float64
c    30.4
dtype: float64


In [ ]:
import pandas as pd
sales = pd.Series([1200,850,1500,950,2000],index=['monday','tuesday','wednesday','thursday','friday'])
print(sales)
print(sales.max())
print(sales.min())
print(sales.sum())
print(sales[sales<1000])

monday       1200
tuesday       850
wednesday    1500
thursday      950
friday       2000
dtype: int64
2000
850
6500
tuesday     850
thursday    950
dtype: int64


In [6]:
#function
import pandas as pd
data = [10, 20, 30,30, 40, 50,50]
s=pd.Series(data)
print(s)
print("with functions:")
print(s.unique()) #remove repeating numbers/data
print(s.nunique()) #return the count of unique data
print(s.value_counts())#how many times a data is repeated


0    10
1    20
2    30
3    30
4    40
5    50
6    50
dtype: int64
with functions:
[10 20 30 40 50]
5
30    2
50    2
10    1
20    1
40    1
Name: count, dtype: int64


In [13]:
import pandas as pd
data = [10, 20, 30,None, 40, 50,50,None]
s=pd.Series(data)

print(s.isnull())
print(s.notnull())

#what is the diffrence?


0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
dtype: bool
0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
dtype: bool


In [14]:
print(s.isna())
print(s.notna())


0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
dtype: bool
0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
dtype: bool


In [15]:
print(s.dropna())

0    10.0
1    20.0
2    30.0
4    40.0
5    50.0
6    50.0
dtype: float64
